### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by rahulnwn** [ameen-browserstack/KeyServer#1]
- Use bundler and Gemfile for dependencies so that everyone can run it locally.
- Thread.new without mutex changing the same variable. This will fail during race condition. Not tested properly.
  - https://github.com/ameen-browserstack/KeyServer/blob/master/keyserver.rb#L10
  - https://github.com/ameen-browserstack/KeyServer/blob/master/keyserver.rb#L35
- This code will only work with single threaded, single process server which will serve requests one by one. In other conditions, code will break.
- Are specs running locally without any spec_helper file or without `require rspec` in the file?
- There should be separate specs to check if served key is blocked and served key is not available. It shouldn't be inside unblock key spec.
  - https://github.com/ameen-browserstack/KeyServer/blob/master/keyserver_spec.rb#L41-L44
- Avoid multiple assertions inside 1 test. Divide in separate tests.

**Comment by ameen-browserstack** [comment]
I have resolved the issues.
